services:

  my-sba:
    image: openjdk:21
    platform: linux/amd64
    container_name: mysbaimage
    ports:
      - 8080:8080
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - my-db
    networks:
      - shared-net
    volumes:
      - ./build/libs:/app
    working_dir: /app
    entrypoint: ["java", "-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000", "-jar", "/app/UserServiceProject-0.0.1-SNAPSHOT.jar"]

  my-db:
    image: mongo:4.4
    platform: linux/amd64
    container_name: mongodbimage
    ports:
      - 27017:27017
    networks:
      - shared-net

networks:
  shared-net:
    external: true