version: '3.8' # o la tua versione di docker-compose

services:

  my-sba:
    image: openjdk:21
    platform: linux/amd64
    container_name: mysbaimage
    ports:
      - 8080:8080
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      my-db:
        condition: service_healthy # <--- Dipendenza con controllo dello stato di salute
    networks:
      - shared-net
    volumes:
      - ./build/libs:/app
    working_dir: /app
    entrypoint: ["java", "-Xdebug", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000", "-jar", "/app/UserServiceProject-0.0.1-SNAPSHOT.jar"]

  my-db:
    image: mongo:4.4
    platform: linux/amd64
    container_name: mongodbimage
    ports:
      - 27017:27017
    networks:
      - shared-net
    healthcheck: # <--- Aggiungiamo un health check
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping').ok" ] # <--- CAMBIATO DA mongosh A mongo QUI!
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s # Puoi provare anche 30s o 40s se l'errore persiste, ma 20s di solito basta.

networks:
  shared-net:
    driver: bridge